/**
 * Contract library — metadata for all studio agreement templates.
 * Used by ownership.html; templates render via assets/templates/contract.html?id=
 */
(function (global) {
  const STAGES = [
    {
      id: "before",
      label: "Before work starts",
      description: "Onboard clients, define scope, and protect both parties before any work begins.",
      icon: "01",
    },
    {
      id: "during",
      label: "During the project",
      description: "Manage scope changes, revisions, pauses, and payment issues while work is in progress.",
      icon: "02",
    },
    {
      id: "after",
      label: "After delivery",
      description: "Confirm acceptance, transfer rights, and close out completed projects.",
      icon: "03",
    },
    {
      id: "ongoing",
      label: "Ongoing relationships",
      description: "Retainers, referrals, partnerships, and long-term brand usage agreements.",
      icon: "04",
    },
  ];

  const CATEGORIES = [
    { id: "core", label: "Core Business Agreements" },
    { id: "payment", label: "Payment & Financial Protection" },
    { id: "ip", label: "Intellectual Property Agreements" },
    { id: "project", label: "Project-Specific Agreements" },
    { id: "management", label: "Client Management Protection" },
    { id: "legal", label: "Legal Protection" },
  ];

  const CONTRACTS = [
    // ── Core Business ──
    {
      id: "msa",
      title: "Master Design Services Agreement",
      category: "core",
      stage: "before",
      frequency: "Use almost every time",
      description: "Your main freelancer agreement covering scope, payment, revisions, IP, confidentiality, and termination.",
      useFor: ["Graphic design", "Branding", "UI/UX", "Product design", "Websites", "Marketing design"],
      includes: ["Scope of services", "Payment terms", "Deadlines", "Client responsibilities", "Revisions", "Communication", "Confidentiality", "Intellectual property", "Portfolio rights", "Termination", "Liability limitations"],
      href: "assets/templates/contract.html?id=msa",
    },
    {
      id: "sow",
      title: "Statement of Work",
      category: "core",
      stage: "before",
      frequency: "Use almost every time",
      description: "Project-specific attachment to your MSA defining deliverables, timeline, milestones, and cost.",
      useFor: ["Branding packages", "Website projects", "Product design", "Any scoped engagement"],
      includes: ["Project name", "Objectives", "Deliverables", "Timeline", "Milestones", "Revision limits", "Cost"],
      example: "Branding Package — logo, color palette, typography, brand guide · 3 concepts · 3 revision rounds",
      href: "assets/templates/contract.html?id=sow",
    },
    {
      id: "proposal",
      title: "Proposal Agreement",
      category: "core",
      stage: "before",
      frequency: "Use almost every time",
      description: "Convert leads into clients with a signed proposal covering problem, solution, process, and investment.",
      useFor: ["New client onboarding", "Project pitches", "Package sales"],
      includes: ["Client problem", "Your solution", "Process", "Deliverables", "Timeline", "Investment", "Acceptance / signature"],
      href: "assets/templates/contract.html?id=proposal",
    },
    {
      id: "intake",
      title: "Client Intake Questionnaire",
      category: "core",
      stage: "before",
      frequency: "Use almost every time",
      description: "Collect brand information, goals, audience, and requirements before kicking off a project.",
      useFor: ["Every new project", "Brand discovery", "Project scoping"],
      includes: ["Brand information", "Goals", "Audience", "Competitors", "Preferences", "Requirements"],
      note: "Not technically a contract, but essential for project setup.",
      href: "assets/templates/contract.html?id=intake",
    },

    // ── Payment ──
    {
      id: "invoice-terms",
      title: "Invoice Terms Agreement",
      category: "payment",
      stage: "before",
      frequency: "Use almost every time",
      description: "Defines deposit requirements, payment schedule, late fees, accepted methods, and refund policy.",
      useFor: ["All paid projects", "Standalone billing terms"],
      includes: ["Deposit requirements", "Payment schedule", "Late fees", "Accepted payment methods", "Refund policy"],
      example: "50% deposit before commencement. Remaining balance due before final files are released.",
      href: "assets/templates/contract.html?id=invoice-terms",
    },
    {
      id: "payment-plan",
      title: "Payment Plan Agreement",
      category: "payment",
      stage: "before",
      frequency: "As needed",
      description: "Structured milestone-based payments for larger projects.",
      useFor: ["Branding packages", "Websites", "Product design", "SaaS projects"],
      includes: ["Upfront percentage", "Milestone payments", "Final delivery payment", "Late payment terms"],
      example: "40% upfront · 30% milestone completion · 30% final delivery",
      href: "assets/templates/contract.html?id=payment-plan",
    },
    {
      id: "retainer",
      title: "Retainer Agreement",
      category: "payment",
      stage: "ongoing",
      frequency: "As needed",
      description: "Recurring monthly design support with defined hours, response times, and billing terms.",
      useFor: ["Monthly branding support", "Product design support", "Marketing design"],
      includes: ["Monthly design hours", "Priority support", "Response times", "Unused hours", "Billing"],
      href: "assets/templates/contract.html?id=retainer",
    },
    {
      id: "late-payment",
      title: "Late Payment / Collections Agreement",
      category: "payment",
      stage: "during",
      frequency: "As needed",
      description: "Covers late fees, work suspension, collection costs, and ownership retention until paid.",
      useFor: ["Overdue invoices", "Payment disputes", "Collections"],
      includes: ["Late fees", "Suspension of work", "Collection costs", "Ownership retention until paid"],
      href: "assets/templates/contract.html?id=late-payment",
    },

    // ── Intellectual Property ──
    {
      id: "ip-assignment",
      title: "Intellectual Property Assignment Agreement",
      category: "ip",
      stage: "after",
      frequency: "As needed",
      description: "Transfers full ownership of creative work to the client upon payment.",
      useFor: ["Full logo ownership", "Exclusive rights", "Trademark ability"],
      includes: ["Assignment of rights", "Payment condition", "Excluded materials", "Warranties"],
      example: "Upon full payment, Designer assigns ownership of the final approved artwork to Client.",
      href: "assets/templates/contract.html?id=ip-assignment",
    },
    {
      id: "design-license",
      title: "Design License Agreement",
      category: "ip",
      stage: "after",
      frequency: "Use often",
      description: "You retain ownership and license usage rights to the client.",
      useFor: ["Logos", "Illustrations", "Artwork", "Apparel designs", "Templates"],
      includes: ["Usage scope", "Term", "Exclusive / non-exclusive rights", "Restrictions", "Portfolio rights"],
      href: "assets/templates/design-license-agreement.html",
    },
    {
      id: "copyright-transfer",
      title: "Copyright Transfer Agreement",
      category: "ip",
      stage: "after",
      frequency: "As needed",
      description: "Formal transfer of copyright ownership for creative works.",
      useFor: ["Illustrations", "Brand assets", "Marketing graphics", "Creative works"],
      includes: ["Copyright assignment", "Work description", "Payment condition", "Moral rights waiver"],
      href: "assets/templates/contract.html?id=copyright-transfer",
    },
    {
      id: "trademark-usage",
      title: "Trademark Usage Agreement",
      category: "ip",
      stage: "ongoing",
      frequency: "As needed",
      description: "Governs logo usage, brand standards, modifications, and trademark responsibilities.",
      useFor: ["Logo deliverables", "Brand mark licensing", "Co-branding"],
      includes: ["Logo usage rules", "Brand standards", "Modifications", "Trademark responsibilities"],
      href: "assets/templates/contract.html?id=trademark-usage",
    },
    {
      id: "font-asset-license",
      title: "Font & Asset Licensing Agreement",
      category: "ip",
      stage: "before",
      frequency: "As needed",
      description: "Protects you from liability related to fonts, stock photos, icons, templates, and third-party assets.",
      useFor: ["Projects using licensed assets", "Client-supplied materials", "Stock imagery"],
      includes: ["Font licensing", "Stock photo terms", "Icon / template usage", "Client-supplied asset warranties"],
      href: "assets/templates/contract.html?id=font-asset-license",
    },

    // ── Project-Specific ──
    {
      id: "logo-design",
      title: "Logo Design Agreement",
      category: "project",
      stage: "before",
      frequency: "Use often",
      description: "Covers concepts, sketches, revisions, final files, ownership, and trademark responsibility.",
      useFor: ["Logo projects", "Wordmarks", "Brand marks"],
      includes: ["Concepts", "Sketches", "Revisions", "Final files", "Ownership", "Trademark responsibility"],
      href: "assets/templates/contract.html?id=logo-design",
    },
    {
      id: "branding",
      title: "Branding Agreement",
      category: "project",
      stage: "before",
      frequency: "Use often",
      description: "Full identity project covering logo, colors, typography, guidelines, and collateral.",
      useFor: ["Brand identity packages", "Rebrands", "Startup branding"],
      includes: ["Logo", "Colors", "Typography", "Brand guidelines", "Social templates", "Packaging"],
      href: "assets/templates/contract.html?id=branding",
    },
    {
      id: "ui-ux",
      title: "UI/UX Design Agreement",
      category: "project",
      stage: "before",
      frequency: "Use often",
      description: "Product design covering research, wireframes, prototypes, design systems, and developer handoff.",
      useFor: ["Web apps", "Mobile apps", "SaaS platforms", "Dashboard design"],
      includes: ["User research", "Wireframes", "User flows", "Prototypes", "Figma files", "Design systems", "Developer handoff", "Testing"],
      href: "assets/templates/contract.html?id=ui-ux",
    },
    {
      id: "product-design",
      title: "Product Design Agreement",
      category: "project",
      stage: "before",
      frequency: "As needed",
      description: "Physical or digital product design from research through specifications and manufacturing considerations.",
      useFor: ["Physical products", "Digital products", "Hardware interfaces"],
      includes: ["Research", "Concepts", "Prototyping", "Specifications", "Manufacturing considerations", "Ownership"],
      href: "assets/templates/contract.html?id=product-design",
    },
    {
      id: "website-design",
      title: "Website Design Agreement",
      category: "project",
      stage: "before",
      frequency: "Use often",
      description: "Design-only website projects covering sitemap, wireframes, mockups, revisions, and handoff.",
      useFor: ["Marketing sites", "Landing pages", "Design-only web projects"],
      includes: ["Sitemap", "Wireframes", "Mockups", "Design revisions", "Handoff"],
      href: "assets/templates/contract.html?id=website-design",
    },
    {
      id: "website-dev",
      title: "Website Design + Development Agreement",
      category: "project",
      stage: "before",
      frequency: "As needed",
      description: "Full website build covering design, development, hosting, domains, maintenance, and bug fixes.",
      useFor: ["Full website builds", "Custom-coded sites"],
      includes: ["Development", "Hosting", "Domains", "Maintenance", "Bugs", "Third-party tools"],
      href: "assets/templates/contract.html?id=website-dev",
    },
    {
      id: "saas-dev",
      title: "SaaS / Product Development Agreement",
      category: "project",
      stage: "before",
      frequency: "As needed",
      description: "Apps and platforms covering product strategy, UX/UI, development, code ownership, and data handling.",
      useFor: ["SaaS platforms", "Web apps", "Startup products"],
      includes: ["Product strategy", "UX/UI", "Development responsibilities", "Code ownership", "Data handling", "Launch expectations"],
      href: "assets/templates/contract.html?id=saas-dev",
    },
    {
      id: "mobile-app",
      title: "Mobile App Design Agreement",
      category: "project",
      stage: "before",
      frequency: "As needed",
      description: "iOS/Android design with prototypes, developer handoff, and app store requirements.",
      useFor: ["iOS apps", "Android apps", "Cross-platform mobile"],
      includes: ["iOS/Android designs", "Prototype", "Developer handoff", "App store requirements"],
      href: "assets/templates/contract.html?id=mobile-app",
    },
    {
      id: "packaging",
      title: "Packaging Design Agreement",
      category: "project",
      stage: "before",
      frequency: "As needed",
      description: "Product packaging, labels, boxes, and inserts with print-ready deliverables.",
      useFor: ["Product packaging", "Labels", "Boxes", "Inserts"],
      includes: ["Packaging design", "Labels", "Dielines", "Print specifications", "Revisions"],
      href: "assets/templates/contract.html?id=packaging",
    },
    {
      id: "apparel-merch",
      title: "Apparel / Merch Design Agreement",
      category: "project",
      stage: "before",
      frequency: "Use often",
      description: "Shirt and merchandise design covering artwork, mockups, printing, and licensing.",
      useFor: ["T-shirt designs", "Merchandise", "Apparel graphics"],
      includes: ["Artwork creation", "Mockups", "Printing responsibilities", "Garment sourcing", "Production approvals", "Licensing / ownership"],
      href: "assets/templates/contract.html?id=apparel-merch",
    },

    // ── Client Management ──
    {
      id: "change-order",
      title: "Change Order Agreement",
      category: "management",
      stage: "during",
      frequency: "As needed",
      description: "Document scope creep and additional work with updated fees and timeline.",
      useFor: ["Out-of-scope requests", "Additional pages", "Extra deliverables"],
      includes: ["Original scope reference", "Additional work description", "Additional fee", "Timeline impact"],
      example: "Additional landing page requested outside original agreement: +$750.",
      href: "assets/templates/contract.html?id=change-order",
    },
    {
      id: "revision-policy",
      title: "Revision Policy Agreement",
      category: "management",
      stage: "during",
      frequency: "Use often",
      description: "Defines revision rounds, what counts as a revision, and additional revision pricing.",
      useFor: ["All design projects", "Standalone revision terms"],
      includes: ["Number of revisions", "What counts as a revision", "Additional revision pricing"],
      href: "assets/templates/contract.html?id=revision-policy",
    },
    {
      id: "project-pause",
      title: "Project Pause Agreement",
      category: "management",
      stage: "during",
      frequency: "As needed",
      description: "Formalize pauses when clients disappear, including restart fees and deposit terms.",
      useFor: ["Inactive clients", "Delayed projects", "Client unavailability"],
      includes: ["Pause duration", "Restart fees", "Timeline changes", "Deposits becoming non-refundable"],
      href: "assets/templates/contract.html?id=project-pause",
    },
    {
      id: "cancellation",
      title: "Project Cancellation / Termination Agreement",
      category: "management",
      stage: "after",
      frequency: "As needed",
      description: "End a project cleanly with fees owed, work completed, and ownership rights defined.",
      useFor: ["Early termination", "Mutual cancellation", "Breach resolution"],
      includes: ["Termination reason", "Fees owed", "Work completed", "Ownership rights", "File delivery"],
      href: "assets/templates/contract.html?id=cancellation",
    },
    {
      id: "final-approval",
      title: "Final Approval & Acceptance Form",
      category: "management",
      stage: "after",
      frequency: "Use almost every time",
      description: "Client confirms work approved, deliverables received, and project completed.",
      useFor: ["Project closeout", "Final delivery", "Payment release"],
      includes: ["Work approved", "Deliverables received", "Project completed", "Signature"],
      href: "assets/templates/contract.html?id=final-approval",
    },

    // ── Legal Protection ──
    {
      id: "nda",
      title: "Non-Disclosure Agreement",
      category: "legal",
      stage: "before",
      frequency: "As needed",
      description: "Protects confidential startup ideas, business plans, product concepts, and private information.",
      useFor: ["Startup clients", "Pre-project discussions", "Sensitive concepts"],
      includes: ["Confidential information definition", "Obligations", "Exclusions", "Term", "Remedies"],
      href: "assets/templates/contract.html?id=nda",
    },
    {
      id: "mutual-nda",
      title: "Mutual NDA",
      category: "legal",
      stage: "before",
      frequency: "As needed",
      description: "Both parties protect each other's confidential information.",
      useFor: ["Collaborative projects", "Partnership discussions", "Co-development"],
      includes: ["Mutual obligations", "Confidential information", "Term", "Return of materials"],
      href: "assets/templates/contract.html?id=mutual-nda",
    },
    {
      id: "independent-contractor",
      title: "Independent Contractor Agreement",
      category: "legal",
      stage: "before",
      frequency: "Use often",
      description: "Clarifies you are not an employee — covers taxes, responsibilities, and relationship status.",
      useFor: ["All freelance engagements", "Tax classification", "Client HR compliance"],
      includes: ["Not an employee", "Taxes", "Responsibilities", "Relationship", "Equipment"],
      href: "assets/templates/contract.html?id=independent-contractor",
    },
    {
      id: "subcontractor",
      title: "Subcontractor Agreement",
      category: "legal",
      stage: "during",
      frequency: "As needed",
      description: "When you hire developers, designers, photographers, or copywriters on a project.",
      useFor: ["Freelancer hires", "Project subcontractors", "Overflow work"],
      includes: ["Scope", "Payment", "IP assignment", "Confidentiality", "Quality standards"],
      href: "assets/templates/contract.html?id=subcontractor",
    },
    {
      id: "work-for-hire",
      title: "Work-for-Hire Agreement",
      category: "legal",
      stage: "before",
      frequency: "As needed",
      description: "Client receives complete ownership from the start of the engagement.",
      useFor: ["Full ownership requests", "Corporate clients", "Work-made-for-hire"],
      includes: ["Work-for-hire designation", "Full ownership transfer", "Payment terms", "Warranties"],
      href: "assets/templates/contract.html?id=work-for-hire",
    },
    {
      id: "referral",
      title: "Referral Agreement",
      category: "legal",
      stage: "ongoing",
      frequency: "As needed",
      description: "Defines referral fees, payment timing, and conditions for people who send you clients.",
      useFor: ["Referral partners", "Affiliate relationships", "Network referrals"],
      includes: ["Referral fee", "Payment timing", "Conditions", "Exclusivity"],
      href: "assets/templates/contract.html?id=referral",
    },
    {
      id: "partnership",
      title: "Partnership Agreement",
      category: "legal",
      stage: "ongoing",
      frequency: "As needed",
      description: "Collaboration terms when partnering with another designer or company.",
      useFor: ["Design partnerships", "Joint ventures", "Co-branded projects"],
      includes: ["Roles", "Revenue split", "IP ownership", "Decision-making", "Termination"],
      href: "assets/templates/contract.html?id=partnership",
    },
  ];

  function getStage(id) {
    return STAGES.find((s) => s.id === id);
  }

  function getCategory(id) {
    return CATEGORIES.find((c) => c.id === id);
  }

  function getContract(id) {
    return CONTRACTS.find((c) => c.id === id);
  }

  function getContractsByStage(stageId) {
    return CONTRACTS.filter((c) => c.stage === stageId);
  }

  function getContractsByCategory(categoryId) {
    return CONTRACTS.filter((c) => c.category === categoryId);
  }

  function getStageCounts() {
    const counts = {};
    STAGES.forEach((s) => {
      counts[s.id] = CONTRACTS.filter((c) => c.stage === s.id).length;
    });
    return counts;
  }

  global.ContractLibrary = {
    STAGES,
    CATEGORIES,
    CONTRACTS,
    getStage,
    getCategory,
    getContract,
    getContractsByStage,
    getContractsByCategory,
    getStageCounts,
  };
})(typeof window !== "undefined" ? window : globalThis);
